calangos-lizard-ideal-temperature 38
calangos-lizard-max-temperature 50
calangos-lizard-min-temperature 15
calangos-lizard-temperature-tolerance 2
calangos-lizard-max-hours-without-food 168
calangos-lizard-max-hours-with-low-hidration 48
calangos-lizard-humidity-affects-hidration 40
calangos-lizard-humidity-param 10
calangos-lizard-min-hydration 45
calangos-lizard-min-energy 5
calangos-lizard-energy-cost-low-temperature 0.05
calangos-lizard-energy-cost-high-temperature 0.05
calangos-lizard-thermal-equilibrium-speed 0.1